<?php if($this->formEnable) : ?>
    <?php if($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>
        <h2 style="color: #fff;" id="successMessage">Dziękujemy za przesłanie wiadomości!</h2>
        <script>
            $(document).ready(function () {
                $("html, body").animate({
                    scrollTop: $('#successMessage').offset().top - $(window).height()/2.5
                }, 1);
            });
        </script>
    <?php endif ?>
    <?php if($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>
        <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
            <script>
                $(document).ready(function () {
                    var offsetScroll = -50; //Offset of 20px
                    $("html, body").animate({
                        scrollTop: $('#formularz').offset().top + offsetScroll
                    }, 1);
                });
            </script>
        <?php endif; ?>
        <div id="formularz">
            <div class="blockContent contFormula">
                <div class="row">
                    <div class="medium-12 large-12 small-12 columns">
                        <h2><?php echo $this->formSectionTitle; ?></h2>
                    </div>
                </div>
                <form action="<?php echo $this->contactForm->getAction()?>" method="<?php echo $this->contactForm->getMethod();?>"
                      class="form">
                    <div class="large-4 medium-12 small-12 columns">
                        <?php echo $this->contactForm->email->renderViewHelper(); ?>
                        <?php echo $this->contactForm->email->renderErrors() ?>
                    </div><!-- large-6 medium-6 columns -->
                    <div class="large-4 medium-12 small-12 columns">
                        <?php echo $this->contactForm->phone->renderViewHelper(); ?>
                        <?php echo $this->contactForm->phone->renderErrors() ?>
                    </div><!-- large-6 medium-6 columns -->
                    <div class="large-4 medium-12 small-12 columns">
                        <?php echo $this->contactForm->subject->renderViewHelper(); ?>
                        <?php echo $this->contactForm->subject->renderErrors() ?>
                    </div><!-- large-12 columns -->
                    <div class="medium-12 large-12 small-12 columns last-box">
                        <?php echo $this->contactForm->message->renderViewHelper(); ?>
                        <?php echo $this->contactForm->message->renderErrors() ?>
                    </div><!-- large-12 columns -->
                <?php if($this->contactForm->has('rodoRegulations')): ?>
                    <div class="medium-12 large-12 small-12 columns last-box">
                        <div class="offerContent">
                            <?php echo $this->contactForm->rodoRegulations->renderViewHelper(); ?>
                            <?php echo $this->contactForm->rodoRegulations->renderErrors() ?>
                        </div>
                    </div>
                    <?php endif; ?>
                    <!-- large-12 columns -->
                    <div class="pnlSend">
                        <div class="large-1 medium-3 small-12 columns" style="padding-left: 0;">&nbsp;</div>
                        <div class="large-7 medium-9 small-12 columns" style="padding-left: 0;">

                            <div class="pull-left">
                                <div id="captchaContainer">
                                    <?php echo $this->contactForm->captcha->render() ?>
                                </div>
                            </div>
                        </div>
                        <div class="large-4 medium-12 small-12 columns" style="padding-left: 0;">
                            <?php echo $this->contactForm->send->renderViewHelper(); ?>
                        </div>
                    </div> <!-- pnlSend -->
                </form>
            </div><!-- blockContent -->
        </div><!-- formularz -->
    <?php endif; ?>
<?php endif; ?>


