<?php if($this->user) : ?>
    <?php if($this->mapApiKeyEnable) : ?>
        <iframe data-src="<?php echo $this->baseUrl('map'); ?>" id="mapFrame"></iframe>
    <?php else: ?>
        <iframe data-src="<?php echo $this->serverTechnicalUrl('map'); ?>" id="mapFrame"></iframe>
    <?php endif; ?>
<?php else: ?>
    <iframe data-src="<?php echo $this->baseUrl('map'); ?>" id="mapFrame"></iframe>
<?php endif; ?>
<script type="text/javascript">
    function initMap() {
        $('.mapInvoker').bind('click.initmap', function() {
            $('#mapFrame').attr('src', $('#mapFrame').attr('data-src'));
            $(this).unbind('click.initmap');
        });
    }
    $(document).ready(function() {
        initMap();
    });
</script>